PDS/PDS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from mainapp import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    url('^admin/',admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'^venlogin/$',views.ven_login,name='ven_login'),
    url(r'^Packlogin/$',views.Pack_login,name='Pack_login'),
    url(r'^requestreturn/(?P<pk>\d+)/$',views.request_return,name='request_return'),
    url(r'^checkreturn/(?P<pk>\d+)/$',views.check_return,name='check_return'),
    url(r'^venHome/(?P<pk>\d+)/$',views.ven_Home,name='ven_Home'),
    url(r'^PackHome/(?P<pk>\d+)/$',views.Pack_Home,name='Pack_Home'),
]


PDS/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Vendor(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)
    v_id = models.CharField(max_length=10)
    v_address = models.CharField(max_length=200,null=False)
    v_description = models.CharField(max_length=300)
    v_phoneNum = models.CharField(max_length=10)


    def __str__(self):
        return self.name

class Unit(models.Model):
	u_name= models.CharField(max_length=100)
	u_address = models.CharField(max_length=300)
	u_contact = models.CharField(max_length=10)

	def __str__(self):
		return self.u_name


class Packaging(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    p_id = models.CharField(max_length=10)
    p_contact = models.CharField(max_length=10)
    p_UnitName=models.ForeignKey(Unit, related_name='unit_id', on_delete=models.CASCADE,)


    def __str__(self):
        return self.name


recieved_choices = [('Yes','Yes'),('No','No')]
class Family(models.Model):
	f_id = models.CharField(max_length=10,unique=True)
	f_recieve = models.CharField(max_length=10,choices=recieved_choices,default='No')
	f_total= models.IntegerField(null=True,default=0)

	def __str__(self):
		return self.f_id




item_choices = [('Rice','Rice'),('Wheat','Wheat'),('Sugar','Sugar')] 
quan_choices = [('1','1'),('2','2'),('4','4')]

class item(models.Model):
	i_name = models.CharField(max_length=20,choices=item_choices)
	i_quantity = models.IntegerField(choices=quan_choices)
	i_barcode = models.CharField(max_length=20,default=0)
	i_vendor=models.ForeignKey(Vendor, related_name='i_ven_id', on_delete=models.CASCADE,)
	i_pack=models.ForeignKey(Packaging, related_name='i_pack_id', on_delete=models.CASCADE,)
	i_fam=models.ForeignKey(Family, related_name='i_fam_id', on_delete=models.CASCADE,blank=True, null=True)

	def __str__(self):
		newname=i_fam.f_id + ' ' + i_name 
		return self.newname


class Customer(models.Model):
	c_aadhar = models.CharField(max_length=12,unique=True)
	c_name = models.CharField(max_length=100)
	c_dob = models.DateField()
	c_family = models.ForeignKey(Family, related_name='c_fam_id', on_delete=models.CASCADE,)


	def __str__(self):
		return self.c_name

PDS/mainapp/views.py
from django.shortcuts import render
from .models import Vendor,Packaging,Customer,item,Family
from django.shortcuts import redirect
from django.utils import timezone



def home(request):
	return render(request,'home.html')
	
	
def ven_login(request):
	if request.method == 'POST':
		v_name = request.POST['v_name']
		v_Id = request.POST['v_Id']
		v_password=request.POST['v_password']

		single_vendor = Vendor.objects.filter(v_id=v_Id).first()
		if single_vendor == None:
			msg="The vendor id is invalid..!"
			back='ven_login'
			return render(request,'error.html',{'msg':msg,'back':back})
			
		else:
			if single_vendor.password == v_password:
				return redirect('ven_Home',pk=v_Id)
			else:
				return render(request,'ven_login.html')
			

	return render(request,'ven_login.html')



def Pack_login(request):
	if request.method == 'POST':
		p_name = request.POST['p_name']
		p_Id = request.POST['p_Id']
		p_password=request.POST['p_password']

		
		
		single_packager= Packaging.objects.filter(p_id=p_Id).first()

		if single_packager == None:
			msg="The Packager id is invalid..!"
			back = "Pack_login"
			return render(request,'error.html',{'msg':msg,'back':back})

		else:
			if single_packager.password == p_password:
				return redirect('Pack_Home',pk=p_Id)
			else:
				return render(request,'Pack_login.html')
			
	return render(request,'Pack_login.html')



def ven_Home(request,pk):
	timezone.now().date()
	cur_date = timezone.now().day
	if request.method == 'POST':
		f_Id = request.POST['f_Id']
		c_adhar=request.POST['c_aadhar']

		if cur_date == 10:
			item.objects.all().delete()
			Family.objects.all().update(f_recieve='No')
			Family.objects.all().update(f_total=0)

		msg = ' '
		try:
			cus_c = Customer.objects.get(c_family=f_Id,c_aadhar=c_adhar)
		except:
			msg = 'Invalid Family Id or Aadhaar Number'
			return render(request,'cust_invalid.html',{'pk':pk,'msg':msg})
		try:
			fam_obj = Family.objects.get(f_id=f_Id,f_recieve='No')
		except:
			msg = 'You have already recieved the monthly comodities.'
			return render(request,'cust_invalid.html',{'pk':pk,'msg':msg})
		if cus_c == None and fam_obj == None:
			b = False

		else:
			b = True

		
		if b:
				
			count = 0
			cust_list = Customer.objects.filter(c_family=f_Id)
			for i in cust_list:
				count = count + 1

			if count > 5:
				count = 5

			rice_quan = count * 4
			wheat_quan = count 
			sugar_quan = 2 

			rice_price = rice_quan * 3
			wheat_price = wheat_quan * 3
			sugar_price = 2 * 10

			total_price = rice_price + wheat_price + sugar_price

			rice_list = item.objects.filter(i_name='Rice',i_vendor=pk,i_fam=None)

			i=0
			for j in rice_list:
				if i<count:
					j.i_fam_id=f_Id
					j.save()
					i=i+1

			wheat_list = item.objects.filter(i_name='Wheat',i_vendor=pk,i_fam=None)

			i=0
			for j in wheat_list:
				if i<count:
					j.i_fam_id=f_Id
					j.save()
					i=i+1

			sugar_list = item.objects.filter(i_name='Sugar',i_vendor=pk,i_fam=None)

			i=0
			for j in sugar_list:
				if i<1:
					j.i_fam_id=f_Id
					j.save()
					i=i+1
			Family.objects.filter(f_id=f_Id).update(f_total=total_price)
			Family.objects.filter(f_id=f_Id).update(f_recieve='Yes')
			return render(request,'cust_page.html',{'cust_list':cust_list,'rice_quan':rice_quan,'wheat_quan':wheat_quan,'sugar_quan':sugar_quan,'rice_price':rice_price,'wheat_price':wheat_price,'sugar_price':sugar_price,'total_price':total_price,'pk':pk})	
		else:
			return render(request,'ven_home.html',{'pk':pk})
		# else:
		# 	return render(request,'ven_home.html',{'pk':pk})
	return render(request,'ven_home.html',{'pk':pk})	


def Pack_Home(request,pk):
	i_list = item.objects.all()
	v_list = Vendor.objects.all()
	if request.method == 'POST':
		i_id = request.POST['i_id']
		i_unique = request.POST['i_unique']
		ven_id=request.POST['v_id']

		if i_id == "1":
			quan = 4
			naam = "Rice"
		elif i_id == "2":
			quan = 1
			naam = "Wheat"
		else:
			quan = 2
			naam = "Sugar"

		
		newitem = item.objects.create(
			i_name = naam,
			i_quantity = quan,
			i_vendor = Vendor.objects.get(v_id=ven_id),
			i_barcode=i_unique,
			i_pack = Packaging.objects.get(p_id=pk),
			i_fam = None
			)
		# back='Pack_login'
		return render(request,'Pack_home.html',{'i_list':i_list,'v_list':v_list,'pk':pk})
	return render(request,'Pack_home.html',{'i_list':i_list,'v_list':v_list,'pk':pk})


def request_return(request,pk):
	rice_list = item.objects.filter(i_fam=None,i_name='Rice')
	wheat_list = item.objects.filter(i_fam=None,i_name='Wheat')
	sugar_list = item.objects.filter(i_fam=None,i_name='Sugar')



	return render(request,'returning_page.html',{'rice_list':rice_list,'wheat_list':wheat_list,'sugar_list':sugar_list,'pk':pk})

def check_return(request,pk):
	rice_list = item.objects.filter(i_fam=None,i_name='Rice',i_vendor=pk)
	wheat_list = item.objects.filter(i_fam=None,i_name='Wheat',i_vendor=pk)
	sugar_list = item.objects.filter(i_fam=None,i_name='Sugar',i_vendor=pk)

	a = item.objects.filter(i_vendor=pk).count()
	b = item.objects.filter(i_vendor=pk,i_fam=None).count()
	r  = item.objects.filter(i_vendor=pk,i_name='Rice',i_fam=None).count()	
	w  = item.objects.filter(i_vendor=pk,i_name='Wheat',i_fam=None).count()	
	s  = item.objects.filter(i_vendor=pk,i_name='Sugar',i_fam=None).count()	

	rp = r *3
	wp = w * 3
	sp = s * 10

	t = rp + wp  + sp
	return render(request,'check_return.html',{'a':a,'b':b,'r':r,'w':w,'s':s,'rp':rp,'wp':wp,'sp':sp,'t':t,'rice_list':rice_list,'wheat_list':wheat_list,'sugar_list':sugar_list,'pk':pk})








PDS/templates/Pack_home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PDS-Packer Home</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
	body {
				background-color: #dfd6ff;
         }
         button {
					  font:  20px Arial;
					  text-decoration: Helvetica;
					  background-color:green;
					  color: white;
					  padding: 5px 10px 5px 10px;
					  border-top: 1px solid #CCCCCC;
					  border-right: 1px solid #333333;
					  border-bottom: 1px solid #333333;
					  border-left: 1px solid #CCCCCC;
					}
			div {background-color: #dfd6ff;}
		
	.row_justify-content-center {position:relative;top:50px;left:400px;border-color:black;border-width: 3px;}
	.form-control {background-color: #f1edff;}
	h1 {position :relative;top:5px;left:500px;font-family: "cursive", cursive, cursive;font-weight: 900;}
	</style>
</head>
<body>
{% block content %}
	<form method='POST'>
	{% csrf_token %}
	<br>
	<centre><h1>Item Update</h1></centre>
	<div class="row_justify-content-center" >     
   		<div class="col-lg-4 col-md-10 col-sm-10">   
   		    <div class="card">    
   		         <div class="card-body">
	<div class='form-group'>

		<label for='id_i_Id'>Item</label>
		
		<select id='id_i_Id' name='i_id'>
		  	<option value= "1">Rice</option>
		  	<option value= "2">Wheat</option>
		  	<option value= "3">Sugar</option>

		</select>
		
	</div>

	<div class='form-group'>
		<label for='id_i_unique'>Enter the bar code number</label>
		<input type='text' class='form-control' id='id_i_unique' name='i_unique'>
	</div>

	<div class='form-group'>
		<label for="id_v_id">vendor name</label>
		<!-- <input type="text" class="form-control" id="id_v_id" name="v_id"> -->
		
		<select id='id_v_id' name='v_id'>
			{% for i in v_list %}
		  		<option value= "{{ i.v_id }}">{{ i.name }}</option>
			{% endfor %}
		  	

		</select>
		
	</div>

	<center><button type="submit" class="btn btn-success">Add item</button>
	</form><br><br><br>
	
	<center><a href="{%url 'Pack_login' %}" button class="btn btn-danger" >Log Out</a>


</div>

</div>
</div>
</div>
<br><br><br>

<center><a href="{%url 'request_return' pk %}"><button type="submit" class="btn btn-success">Check the available return</button></a><br><br><br><br><br><br><br>
{% endblock %}
</body>
</html>


PDS/templates/Pack_login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PDS-Manufacturer Login</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
	<style>
	body {
				background-color: #dfd6ff;
         }
         
			div {background-color: #dfd6ff;}
						center {background-color: #dfd6ff;}

	.row_justify-content-center {position:relative;top:50px;left:400px;border-color:black;border-width: 3px;}
	.form-control {background-color: #f1edff;}
	h1 {position :relative;top:5px;left:485px;font-family: "cursive", cursive, cursive;font-weight: 900;}
	</style> 
</head>
<body>
{% block content %}
	<form method='POST'>
	{% csrf_token %}
	<br>
	<centre><h1>Packer Login</h1></centre>
	<div class="row_justify-content-center" >     
   		<div class="col-lg-4 col-md-10 col-sm-10">   
   		    <div class="card">    
   		         <div class="card-body">
	<div class='form-group'>
		<label for='id_p_name'>Packer Name</label>
		<input type='text' class='form-control' id='id_p_name' name='p_name'>
	</div>
	<div class='form-group'>
		<label for="id_p_Id">Packer Id</label>
		<input type='text' class='form-control' id='id_p_Id' name='p_Id'>
	</div>
	<div class='form-group'>
		<label for="id_p_password">Password</label>
		<input type="Password" class="form-control" id="id_p_password" name="p_password">
	</div>

	<center><button type="submit" class="btn btn-success">Login</button></center>
	</form>
	<br><br><br>
	<center><a href="{%url 'home' %}" button class="btn btn-danger" >Home</a>

</div>
</div>
</div>
</div>




{% endblock %}
</body>
</html>

PDS/templates/check_return.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Return</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
	body {background-color:#e5c3a5;}
	h3 {font-family: "cursive", cursive, cursive;}
	h5 {font-family: "Luminari", Luminari ,fantasy;}
	#sav {font-size: 60px;border-style: }
</style>
</head>
<body>
{% block content %}<br><br>
		
		<table class="table">
		<thead class="thead-inverse">
			<tr >
				
				<th><center>Item<br> Name</th>
				<th><center>Vendor <br>Name</th>
				<th><center>Item <br>Barcode</th>
				
				
			</tr>
		</thead>
		<tbody>


		{% for i in rice_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
				
			</tr>
		{% endfor %}

		{% for i in wheat_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
			</tr>
		{% endfor %}
		{% for i in sugar_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
			</tr>
		{% endfor %}
			
		</tbody>

		</table>
		

		<h3><center><strong>Total Items alloted: </strong>{{ a }}</center></h3><br>
		<h5><center><strong>Remaining Rice Items: </strong>{{ r }}<strong>   <br>  Rice amount saved : </strong>Rs.{{ rp }}</center></h5>
		<h5><center><strong>Remaining Wheat Items: </strong>{{ w }}<strong>   <br> Wheat amount saved : </strong>Rs.{{ wp }}</center></h5>
		<h5><center><strong>Remaining Sugar Items: </strong>{{ s }}<strong>  <br>  Sugar amount saved : </strong>Rs.{{ sp }}</center></h5><br>
		<h3><center><strong>Total Remaining Items: </strong>{{ b }}</center></h3>
		<br>		
		<h3 id="sav"><center><strong>Total amount saved: </strong>Rs.{{ t }}</center></h3><br>
<center><a href="{%url 'ven_Home' pk %}"><button type="submit" class="btn btn-success">Back to Billing</button>
{% endblock %}
</body>
</html>

PDS/templates/cust_invalid.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Error id</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
	<style type="text/css">.btn_btn-success {position: relative;left:-20px;top:100px; 
					font:  17px Arial;
					  text-decoration: Helvetica;
					  background-color:green;
					  color: ;
					  padding: 5px 10px 5px 10px;
					  border-top: 1px solid #CCCCCC;
					  border-right: 1px solid #333333;
					  border-bottom: 1px solid #333333;
					  border-left: 1px solid #CCCCCC;}
					  h3 {font-family: "cursive", cursive, cursive;font-weight: bolder;}
					  </style> 

</head>
<body>
	{% block content %}
	<br><br>
	<h3><b><center>{{ msg }}</h3></b><br>
	<center><a href="{% url 'ven_Home' pk %}" button type="submit" class="btn_btn-success">Back</button></a>
 
	{% endblock %}
</body>
</html>

PDS/templates/cust_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Customer</title>
	<style>
	.table {position: relative;left:100px;border-color:black;border-width: 5px;color: #664529;background-color:#ffe9d6; }
	.tab {position: absolute;left:800px;top:130px;border-color:black;border-width: 5px;background-color:#ffe9d6;color: #664529}
	h1 {position:relative;left:550px;font-family: "cursive", cursive, cursive;font-weight: bolder;}
	h2 {position: relative;left:1055px;top:235px;border-style:dotted;border-width: 6px;border-color: red;width: 210px;padding: 8px;top:-150px;color:green;text-align: right;
	}
	th {border-color: #2e2b38;border-width:5px;color:#3d345e;}
	td {border-color: #2e2b38;border-width:1px;}
	body {
				background-color: #e5c3a5;
         }
	</style>
</head>
<body>
	
	{% block content %}
	<h1>Customer Bill</h1><br /><br />
					<table class="table" border="3" width="500px" cellpadding="20px" cellspacing="5">
		<thead class="thead-inverse">
			<tr id="main">
				
				<th><center>Customer<br> Name</th>
				<th><center>Aadhaar <br>Reg No.</th>
				
				
			</tr>
		</thead>
		<tbody>


		{% for i in cust_list %}

			<tr>
				<td class="align-middle">{{ i.c_name }}</td>
				<td class="align-middle">{{ i.c_aadhar }}</td>
				
			</tr>
		{% endfor %}
			
		</tbody>

		</table>
		<br><br><br>
		<table class="tab" border="3" width="500px" cellpadding="20px" cellspacing="5">
			<tr><th>Product</th>
				<th>Quantity</th>
				<th>Price</th></tr>
			

			<tr><td>Rice</td>
				<td><a>{{ rice_quan }} kg</a><br></td>
				<td><a>Rs. {{ rice_price }}</a><br></td></tr>

			<tr><td>Wheat</td>
				<td><a>{{ wheat_quan }} kg</a><br></td>
				<td><a>Rs. {{ wheat_price }}</a><br></td></tr>

			<tr><td>Sugar</td>
				<td><a>{{ sugar_quan }} kg</a><br></td>
				<td><a>Rs. {{ sugar_price }}</a><br></td></tr>
		</table>
		<br>
		<br>
		<a><h2>Total Price : Rs. {{ total_price }}</h2></a><br>


		
	{% endblock %}
<center><a href="{%url 'ven_Home' pk %}" button class="btn btn-danger" >Logout</a>
</body>

</html>

PDS/templates/error.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Error id</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
	<style type="text/css">.btn_btn-success {position: relative;left:-20px;top:100px; 
					font:  17px Arial;
					  text-decoration: Helvetica;
					  background-color:green;
					  color: ;
					  padding: 5px 10px 5px 10px;
					  border-top: 1px solid #CCCCCC;
					  border-right: 1px solid #333333;
					  border-bottom: 1px solid #333333;
					  border-left: 1px solid #CCCCCC;}</style> 
</head>
<body>
	{% block content %}
	<br><br>
	<h3><b><center>{{ msg }} </h3></b><br>
	<center><a href="{% url back %}" button type="submit" class="btn_btn-success">Back</button></a>
 
	{% endblock %}
</body>
</html>

PDS/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PDS</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
		body {
				background-image: url("static/img/background_home.png"); 
				background-repeat: no-repeat;
				background-size: 1440px 900px;

         }
		h1 {font-family: "Luminari", Luminari ,fantasy;
			}
		h4 { font-family: "Times New Roman", Times, serif;
			}
		a {font-size: 30px;
			font-style: Helvetica;
			color: white;
			background-color: blue;}
			.button {
					  font: bold 30px Arial;
					  text-decoration: Helvetica;
					  background-color:#3a3e44;
					  color: #af8c00;
					  padding: 5px 10px 5px 10px;
					  border-top: 1px solid #CCCCCC;
					  border-right: 1px solid #333333;
					  border-bottom: 1px solid #333333;
					  border-left: 1px solid #CCCCCC;
					}
	div {position: relative;width:1000px;left:150px;text-indent: 50px;}
	h2 {position: relative; width:100px;left:180px;}
	#pa {position: relative;left:40px;top: 20px;}
	#ve {position: relative;left:-40px;top: 20px;}
	</style>
</head>
<body>

{% block content %}


<center>
	<br /><h1 style="color:#560b1a; font-size:50px" >Foolproof Public Distribution System</h1>
		<h4 >Joint initiative by Govt. of India and Govt. of Karnataka</h4><br /><br />
	</center>
	<br /><h2 style="color:#244f00"><strong>About:</strong></h2>
	<div><h3 style="color:#001368"><ol><br /><p>PDS is the largest food distribution network in the world. It has a network of more than 4 lakh Fair price shops that distribute commodities to 16 Crore households at a cost of more than Rs.15,000 Crore.<br /></p>
<p>Of the total loss incurred by the government 39% is distribution leakage loss, 38% is over-allotment loss and 17% is active suspect loss.</p> 
<p>Fool proof public distribution system will control and prevent the losses incurred to the government. Aadhaar cards of a family is linked to Ration card and a smart card will be provided. The biometric data will help in eliminating the ghost cards.
Packing and bar-coding of grains will ensure proper distribution and tracing of the grains.The extras will be accounted back to the government.</p> </h3></div>
<center>
<a id="ve" href="{% url 'ven_login' %}" class="button">Vendor Login</a>
<a id="pa" href="{% url 'Pack_login' %}" class="button">Packager Login</a>
</center>	


{% endblock %}
</body>
</html>

PDS/templates/returning_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Returns</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
		div {background-color: green;}
	</style>
</head>
<body>
{% block content %}

		<table class="table">
		<thead class="thead-inverse">
			<tr >
				
				<th><center>Item<br> Name</th>
				<th><center>Vendor <br>Name</th>
				<th><center>Item <br>Barcode</th>
				
				
			</tr>
		</thead>
		<tbody>


		{% for i in rice_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
				
			</tr>
		{% endfor %}

		{% for i in wheat_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
			</tr>
		{% endfor %}
		{% for i in sugar_list %}

			<tr>
				<td class="align-middle"><center>{{ i.i_name }}</td>
				<td class="align-middle"><center>{{ i.i_vendor }}</td>
				<td class="align-middle"><center>{{ i.i_barcode }}</td>
			</tr>
		{% endfor %}
			
		</tbody>

		</table>
<center><a href="{%url 'Pack_Home' pk %}"> <button type="submit" class="btn btn-success">Assign New Item</button></a>

	
{% endblock %}
</body>
</html>

PDS/templates/ven_home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PDS-Vendor Home</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
	body {
				background-color: #dfd6ff;
				background-repeat: no-repeat;
         }
			div {background-color: #dfd6ff;}
		
	.row_justify-content-center {position:relative;top:50px;left:400px;border-color:black;border-width: 3px;}
	.form-control {background-color: #f1edff;}
	h1 {position :relative;top:5px;left:400px;font-family: "cursive", cursive, cursive;font-weight: 900;}
	</style>
</head>
<body>
{% block content %}
	<form method='POST'>
	{% csrf_token %}
	<br />
	<centre><h1>Customer Authentication</h1></centre>
	<div class="row_justify-content-center" >     
   		<div class="col-lg-4 col-md-10 col-sm-10">   
   		    <div class="card">    
   		         <div class="card-body">
	<div class='form-group'>
		<label for='id_f_Id'>Smart Card Number</label>
		<input type='text' class='form-control' id='id_f_Id' name='f_Id'>
	</div>
	<div class='form-group'>
		<label for="id_c_aadhar">Customer Aadhaar number</label>
		<input type="text" class="form-control" id="id_c_aadhar" name="c_aadhar">
	</div>
	<br>
	<center><button type="submit" class="btn btn-success">Authenticate</button></center>
	</form><br><br><br><br>
	<center><a href="{%url 'check_return' pk %}" button class="btn btn-danger" >Check remaining</a>
</div>
</div>
</div>
</div>


{% endblock %}
</body>
</html>

PDS/templates/ven_login.html
s{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PDS-Vendor Login</title>
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
	<style>
	body {
				background-color: #dfd6ff;
				background-repeat: no-repeat;
         }
         button {
					  font:  20px Arial;
					  text-decoration: Helvetica;
					  background-color:green;
					  color: white;
					  padding: 5px 10px 5px 10px;
					  border-top: 1px solid #CCCCCC;
					  border-right: 1px solid #333333;
					  border-bottom: 1px solid #333333;
					  border-left: 1px solid #CCCCCC;
					}
			div {background-color: #dfd6ff;}
		
	.row_justify-content-center {position:relative;top:100px;left:400px;border-color:black;border-width: 3px;}
	.form-control {background-color: #f1edff;}
	h1 {position :relative;top:5px;left:475px;font-family: "cursive", cursive, cursive;font-weight: 900;}
	#but {position: relative;top:100px; }
	</style>
</head>
<body>
{% block content %}
	<form method='POST'>
	{% csrf_token %}
	<br />
	<centre><h1>Vendor Login</h1></centre>
	<div class="row_justify-content-center" >     
   		<div class="col-lg-4 col-md-10 col-sm-10">   
   		    <div class="card">    
   		         <div class="card-body">
	<div class='form-group'>
		<label for='id_v_name'>Vendor Name</label>
		<input type='text' class='form-control' id='id_v_name' name='v_name'>
	</div>
	<div class='form-group'>
		<label for="id_v_Id">Vendor Id</label>
		<input type='text' class='form-control' id='id_v_Id' name='v_Id'>
	</div>
	<div class='form-group'>
		<label for="id_password">Password</label>
		<input type="Password" class="form-control" id="id_password" name="v_password">
	</div>

	<center><button type="submit" class="btn btn-success">Login</button><br><br><br>
		<center><a href="{%url 'home' %}" button class="btn btn-danger" >Home</a>
	</form>

</div>
</div>
</div>
</div>



{% endblock %}
</body>
</html>