e-tender/g_13/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from tender import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [
	
	url(r'^$',views.home,name='home'),
	url(r'^requesting/(?P<user_data>\w+)/$',views.requesting,name='requesting'),
	#url(r'^bidnow/(?P<pk_t>\d+)/(?P<s>\s*)/$',views.bid_now2,name='bid_now2'),
	url(r'^bidnow/(?P<pk_t>\d+)/(?P<comp_name>\w+)/$',views.bid_now,name='bid_now'),
	url(r'^complaints/$',views.complaints,name='complaints'),
	url('^admin/',admin.site.urls),
	url(r'^sub_departments/(?P<pk>\d+)/$',views.sub_departments,name='sub_departments'),
	url(r'^tenders/(?P<pk>\d+)/$',views.tenders,name='tenders'),
	url(r'^signup/$',accounts_views.signup,name='signup'),
	url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
	url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	url(r'^bid/(?P<pk>\d+)/$',views.bid,name='bid'),
]
# this file contains the urls of all the references


# home -- default home page
# requesting -- it asks for company registeration number
# bid_now -- displays a form which takes the input the bidding price and description
# complaints -- it is a form which accepts all the complaints
# admin -- it is the url for admin login
# sub_departments -- it is the page obtained on clicking dept name which lists all the subdept under that dept
# tenders -- it displays all the tenders under a particular subdept
# signup -- for signing up
# login - for login purpose
# bid -- it shows all the bids of a particular tender

e-tender/tender/models.py
from django.db import models

from django.contrib.auth.models import User

# it is a table which has the department name and image related to that department
class dept_master(models.Model):
	d_name=models.CharField(max_length=30)
	d_image= models.CharField(max_length=50,null=True)
	def __str__(self):
		return (self.d_name)

#it is a table which has the sub dept name and image also it has a forign key from dept_master table which indicate under which dept this comes. 
class sub_dept(models.Model):
	sub_dept_name=models.CharField(max_length=30)
	sub_image= models.CharField(max_length=50,null=True)
	D_Id=models.ForeignKey(dept_master, related_name='department_id', on_delete=models.CASCADE,)
	def __str__(self):
		return (self.sub_dept_name)
		
#it is a table having:
#tender name,image,start date,end date
#it also has forignkeys from dept_master and sub_dept which helps to track under which dept and sub-dept it belongs. 
class tender(models.Model):
	t_name=models.CharField(max_length=30)
	D_Id=models.ForeignKey(dept_master, related_name='department_id1', on_delete=models.CASCADE,)
	Sub_Id=models.ForeignKey(sub_dept, related_name='sub_department_id', on_delete=models.CASCADE,)
	t_description = models.CharField(max_length=100)
	t_image= models.CharField(max_length=50,null=True)
	t_start_period=models.DateTimeField(null=True)
	t_price=models.FloatField()
	t_end_date = models.DateTimeField(null=True)
	def __str__(self):
		return (self.t_name)

	def expired(self):
		import datetime
		from django.utils import timezone
		if self.t_end_date < timezone.now():
			return False
		else:
			return True


#company is the user who wants to bid.
#every company should have a unique registration number.
class company(models.Model):
	#c_user = models.ForeignKey(User,related_name = 'company_user',on_delete=models.CASCADE,null=True,default=0)
	c_name=models.CharField(max_length=30, null=True)
	c_reg_no=models.CharField(max_length=12, unique=True)
	def __str__(self):
		return (self.c_name)



#Complaints is the table which holds the name of the complaint and description about it.
#it is not linked to user/company so that it is anonymous and even admin should not find out.
class complaint(models.Model):
	compl_name = models.CharField(max_length=30, null=True)
	compl_description = models.CharField(max_length=250, null=True)
	def __str__(self):
		return (self.compl_name)


#bidding is the important table linking the company and tender
#it creates a link between the company that has bid and the tender that it has bid.
class bidding(models.Model):
	c_id = models.ForeignKey(company,related_name = 'company_id',on_delete=models.CASCADE,null=False,default=None)
	t_id = models.ForeignKey(tender,related_name = 'tender_id',on_delete=models.CASCADE,)
	b_price = models.FloatField()
	b_description = models.CharField(max_length=100)
	


e-tender/templates/base.html
{% load static %}<!DOCTYPEhtml>
<html>
	<head>
		<meta charset="utf-8">
			<title>{% block title %}e-tender{% endblock %}</title>
				<link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"> 
				{% block stylesheet %}{% endblock %}
	</head>
	<body>
		{% block body %}
		<nav class="navbar navbar-expand-sm navbar-dark " style="background-color:#cb4328;text-align:center;">
		<!--nav style="background-color:white;color : red;"-->
	    <div class="container" style="height: 70px;">
	    	<a class="navbar-brand" href="{%url 'home' %} "style=" font-size: 35px;width:750px;text-align:right"><b>KARNATAKA E-TENDER</b></a>
	    	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
	    		<span class="navbar-toggler-icon"></span>
	    	</button>
	    	<div class="collapse navbar-collapse" id="mainMenu">
				{% if user.is_authenticated %}
				<ul class="navbar-nav ml-auto">
				  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  {{ user.username }}
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href="{%url 'logout' %}">Log out</a>
					</div>
				  </li>
				</ul>
			  {% else %}
        <form class="form-inline ml-auto">
          <a href="{%url 'login' %}" class="btn btn-primary ml-2">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
			<style type="text/css">
#watermark {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:465px;
  top:400px;
}
</style>
			
			
			
	    		
	    		
	    	</div>
	    </div>
		</nav>
	
		{% block content %}
		{% endblock %}	

		
		</div>
	{% endblock body%}
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	</body>
<br>
</html>

e-tender/templates/bid_forms.html
{% extends 'base.html' %}
{% block title %}Bid for the Development of our State{% endblock %}
{% block breadcrumb %}
	<li class='breadcrumb-item'><a href='{%url "home" %}'>Departments</a></li>
	<!--<li class='breadcrumb-item'><a href='{%url "sub_dept_list.html"  %}'>Departments</a></li>
	<li class='breadcrumb-item'><a href='{%url "board_topics" board.pk %}'>{{board.name}}</a></li>-->
	<li class="breadcrumb-item activate">BID</li>
{% endblock %}
{% block content %}
	<form method='POST'>
	{% csrf_token %}
	<br>
	<div class="row justify-content-center" >     
   		<div class="col-lg-4 col-md-10 col-sm-10">   
   		    <div class="card">    
   		         <div class="card-body">
	<div class='form-group'>
		<label for='id_b_price'>Bidding price</label>
		<input type='float' class='form-control' id='id_b_brice' name='bidding_price'>
	</div>
	<div class='form-group'>
		<label for="id_b_description">Bidding Discription</label>
		<textarea class="form-control" id="id_b_description" name="bidding_description" rows="5"></textarea>
	</div>
	<center><button type="submit" class="btn btn-success">Post</button>
	</form>
</div>
</div>
</div>
</div>
{% endblock %}

e-tender/templates/bid_list.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
	<br>
	<div class="row justify-content-center" >     
   		<div class="col-lg-8 col-md-8 col-sm-8">   
   		    <div class="card">    
   		         <div class="card-body">
		{% for bid in bidding_list %}
		<br>
	<a style="font-size: 20px;text-align:right"/><b>Name of the Tender:</b> {{ bid.t_name }} <br>
	<a style=" font-size: 20px;text-align:right"/><b>Department Name:</b>     {{ bid.D_Id.d_name }} <br>
	<a style=" font-size: 20px;text-align:right"/><b>Sub Department Name:</b> {{ bid.Sub_Id.sub_dept_name }} <br>
	<br>
  	<a style="font-size: 20px;text-align:right"/><center><img src="..\..\{{ bid.t_image }}"  style="height: 300px; width: 300px;"/></center><br>
	<a style=" font-size: 15px;text-align:right"/>{{ bid.t_description }}<br>
	<a style=" font-size: 20px;text-align:right"/><b>Project Start Date:</b> {{bid.t_start_period}} <br>
	<a style=" font-size: 20px;text-align:right"/><b>Bidding End Date:</b> {{bid.t_end_date}} <br>
	<a style=" font-size: 20px;text-align:right"/><b>Budget Price(approx) : </b>Rs. {{bid.t_price}}/-<br>
	<br>{% if user.username != 'group_13' %} 
			<center><a href="{% url 'bid_now' bid.id user.username%}" button type="submit" class="btn btn-success">BID NOW</button></a>
		{% endif %}
	<br>
		{% endfor %}
		<br>
		<table class="table">
		<thead class="thead-inverse">
			<tr >
				
				<th><center>Company<br> Name</th>
				<th><center>Company <br>Reg No.</th>
				<th><center>Bidding<br> Price</th>
				<th><center>Bidding <br>Description</th>
				
			</tr>
		</thead>
		<tbody>


		{%for obj in bidding_object %}
			<tr>
				{% if obj == bidding_object.first %}
				<div>
				<tr style="background-color: lightgray">
				<td class="align-middle" style="color: darkgreen"><center>{{ obj.c_id.c_name }}</td>
				<td class="align-middle"style="color: darkgreen"><center>{{ obj.c_id.c_reg_no }}</td>
				<td class="align-middle" style="color: darkgreen"><center>Rs.{{ obj.b_price }}</td>
				<td class="align-middle" style="color: darkgreen"><center>{{ obj.b_description }}</td>
				</tr>
				</div>
				{% else %}
				
				<td class="align-middle"><center>{{ obj.c_id.c_name }}</td>
				<td class="align-middle"><center>{{ obj.c_id.c_reg_no }}</td>
				<td class="align-middle"><center>Rs.{{ obj.b_price }}</td>
				<td class="align-middle"><center>{{ obj.b_description }}</td>
				{% endif %}
			</tr>
			{% endfor %}
			
		</tbody>

	</table>
			
</div>
</div>
</div>
</div>
		
		
		
			
		</body>

	{% endblock %}

e-tender/templates/complaints.html
{% extends 'base.html' %}

{% block title %}ENTER YOUR COMPLAINT DETAILS{% endblock %}


{% block content %}
<br><br>
<div class="row justify-content-center" >     
   		<div class="col-lg-5 col-md-6 col-sm-8">   
   		    <div class="card">    
   		         <div class="card-body">       
   		             <h3 class="card-title">Complaint Form:</h3>   
   		                     <form method="post" novalidate>
								 {% csrf_token %} 
	<div class="form-group">
		<label for="id_compl_name">Complaint Name:</label>
		<input type="text" class="form-control" id="id_compl_name" name="compl_name"><br>
		
	</div>
	<div class="form-group">
		<label for = "id_compl_description">Complaint Description</label>
		<textarea class="form-control" id="id_compl_description" name="compl_description" rows="5"></textarea>
	</div>	
		<center><button type="submit" class="btn btn-success">SUBMIT</button>
		</div> 
    </div>
	</div> 
    </div>
	

</form>
{% endblock %}

e-tender/templates/error.html
{% extends 'base.html' %} 
 {% block content %}
 <br><br>
 <h3><b><center>{{ msg }} </h3></b><br>
<center><a href="{% url 'home' %}" button type="submit" class="btn btn-success">Home</button></a>
 
{% endblock %}

e-tender/templates/home.html
	{% extends 'base.html' %}
{% load static %}
<html>

{% block breadcrumb %}
<li class="breadcrumb-items active">Departments</li>
{% endblock %}


	


{% block content %}
	<head>
		<h1 style="color:#bec22f;"><center><b>ಕರ್ನಾಟಕ ರಾಜ್ಯ ಸರ್ಕಾರ</b></center></h1>
		
<style type="text/css">
#watermark0 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:0px;
  top:0px;
}
#watermark {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:380px;
  top:400px;
}
#watermark1 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:-114px;
  top:-30px;
}
#watermark2 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:890px;
  top:-30px;
}
#watermark3 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:-50px;
  top:930px;
}
#watermark4 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:835px;
  top:930px;
}
#watermark5 {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:375px;
  top:900px;
}
</style>

		
	</head><br>
	<center>
		<div>
  			<img src="static\img\ke.jpg"  style="height: 100px; width: 100px;"/><br><br>
	</div>
	
		
	<h1><a class="btn btn-secondary" style="width: 600px; font-size:20px;background-color:darkgray">DEPARTMENTS OF GOVERNMENT</h1></center></a><br>
	<body><center>
		<div id="watermark0">
  			<img src="static\img\bg.jpg"  style=" height: 1550px; width: 1450px;opacity: 1;"/>
	</div>
			<div id="watermark">
  			<img src="static\img\ke.jpg"  style="height: 600px; width: 600px;opacity: 0.5;"/><br><br>
	</div>
	<div id="watermark1">
  			<img src="static\img\sc1.jpg"  style=" height: 255px; width: 377px;opacity: 1;"/>
	</div>
	<div id="watermark2">
  			<img src="static\img\mp.jpg"  style=" height: 255px; width: 377px;opacity: 1;"/>
	</div>
	<div id="watermark3">
  			<img src="static\img\vs.jpg"  style=" height: 200px; width: 500px;opacity: 1;"/>
	</div>
	<div id="watermark4">
  			<img src="static\img\hc.jpg"  style=" height: 200px; width: 500px;opacity: 1;"/>
	</div>
	<!--<div id="watermark5">
  			<img src="static\img\gk.jpg"  style=" height: 200px; width: 300px;opacity: 1;"/>
	</div>-->


		{% for dm in dept_names %}
			<br><a href="{%url 'sub_departments' dm.id %}" class="btn btn-primary" style="width: 500px">{{dm.d_name}}</a><br>
		{% endfor %}

	</center>
	<div style="margin-top: -475px; margin-left: 25px">
		<div style= "color:white">
			<a class="btn btn-danger" style="width: 260px;">Tenders</a><br>		
		</div>
		<div id="" style="overflow-y: scroll; height: 400px; background: lightgray;width: 260px;">
			{% for i in tender_names %}
				<a ><b>{{ i }}</b></a><br><b>*</b>
				<small style="text-muted d-block;padding-left: 0.5em"> {{ i.D_Id }}</small><br>
				<a style="text-muted d-block;padding-left: 0.6em"> <b>></b></a>
				<small style="text-muted d-block;padding-left: 0.2em"> {{ i.Sub_Id }}</small><br>
				<a >____________________________________</a>
			{% endfor %}
		</div>
			
	</div>

	<div style="margin-top: -445px; margin-left: 1100px">
		<div style= "color: white">
			<a class="btn btn-danger" style="width: 260px;">Complaints</a><br>		
		</div>
		<div id="" style="overflow-y: scroll; height: 400px; background: lightgray;width: 260px;">
			{% for i in compl %}
				
				<a style="padding-left: 0.5em"><b> {{ i.compl_name }}</b></a><br>
				<a style="text-muted d-block;padding-left: 0.6em"> <b>></b></a>
				<small style="text-muted d-block;padding-left: 0.2em"> {{ i.compl_description }}</small><br>
				<a >_____________________________________</a>
			{% endfor %}
		</div>
		<a href="{%url 'complaints' %}" class="btn btn-info" style="width: 260px;color: white"> add complaint</a>
	</div>

	</body>
{% endblock %}



</html>

e-tender/templates/login.html
{% extends 'base.html' %} 
 
{% block title %}
Log in to Your account
{% endblock %} 
 
{% block content %}
<br><br>
   <div class="row justify-content-center" >     
   		<div class="col-lg-4 col-md-6 col-sm-8">   
   		    <div class="card">    
   		         <div class="card-body">       
   		             <h3 class="card-title">Company Log in</h3>   
   		                     <form method="post" novalidate>      
   		                            {% csrf_token %}   
   		                                      {% include 'includes/form.html' %}
   		                                                   <button type="submit" class="btn btn-primary btn-block">Log in</button>           </form>         </div> 
   		                                                           <div class="card-footer text-muted text-center">           New Here? <a href="{% url 'signup' %}">Sign up</a>
   		                                                                    </div>  
   		                                                                         </div>
   		                                                                                <div class="text-center py-2">
   		<small>           <a href="#" class="text-muted">Forgot your password?</a>         </small>       </div>   
   		  </div> 
    </div>
{% endblock %} 

e-tender/templates/requesting.html
{% extends 'base.html' %}

{% block title %}PLEASE ENTER THESE REQUIRED DETAILS{% endblock %}


{% block content %}
<br><br>
<div class="row justify-content-center" >     
   		<div class="col-lg-5 col-md-6 col-sm-8">   
   		    <div class="card">    
   		         <div class="card-body">       
   		             <h3 class="card-title">Enter the company register number:</h3>   
   		                     <form method="post" novalidate>
								 {% csrf_token %} 
	<div class="form-group">
		<label for="company_reg_no"></label>
		<input type="text" class="form-control" id="id_company_reg_no" name="company_reg_no"><br>
		<center><button type="submit" class="btn btn-success">SUBMIT</button>
	</div>
		</div> 
    </div>
	</div> 
    </div>
	

</form>
{% endblock %}

e-tender/templates/signup.html
#{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{%static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container" >
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Company Management</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {%include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{%url 'login' %}">Log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

e-tender/templates/sub_dept_list.html

{% extends 'home.html' %}

{% load static %}


{% block content %}
<style type="text/css">
#watermark {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:0px;
  top:0px;
}
</style>
	
		<center>
			<br>
			
		<body>
		
		<center><a class="btn btn-secondary" style="width:auto;background-color:darkgray"><h2>SUB-DEPARTMENTS OF {{single_dept.d_name}}</h2></center></a><br>
		<div id="watermark">
  			<img src={{single_dept.d_image}}  style="opacity: 1;"/><br><br>
		</div>
		{%for sub in sub_depts %}
			<center><a  href="{% url 'tenders' sub.id%}" class="btn btn-primary" style="width:500px">{{sub.sub_dept_name}}</a></center><br>
		{% endfor %}
			
		</body>

	{% endblock %}

e-tender/templates/tender_list.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li class="breadcrumb-items active">Tender Details</li>
{% endblock %}

<br><h2><b><center>Tender Details</center></b></h2>

{% block content %}
<style type="text/css">
#watermark {
  color: #d0d0d0;
  font-size: 200pt;
  -webkit-transform: rotate(0deg);
  -moz-transform: rotate(0deg);
  position: absolute;
  width: 600px;
  height: 600px;
  margin: 0;
  z-index: -1;
  left:0px;
  top:0px;
}
</style>
<div id="watermark">
  			<img src="..\..\static\img\cbft.jpg"  style=" opacity: 1;"/><br><br>
		</div>
	<table class="table">
		<thead class="thead-inverse">
			<tr>
				<th>Tender no.</th>
				<th>Tender name</th>
				<center><th>Tender Details</th></center>
				<th>Date & Time</th>
				<th>Price</th>
				<th>Bid</th>
			</tr>
		</thead>
		<tbody>
		{%for tend in tenders_list %}
			<tr>
				<td class="align-middle"><center>{{ tend.id }}</center></td>
				<td class="align-top">{{ tend.t_name }}<br>Dept name: {{ tend.D_Id.d_name }}<br>Sub Dept: {{ tend.Sub_Id.sub_dept_name }}</td>
				<td class="align-top"><center><img src="..\..\{{ tend.t_image }}" style="height: 50px; width: 50px;"/><br></center><small style="text-muted d-block">{{ tend.t_description }}</small></td>
				<td class="align-top">Bidding End Date: {{ tend.t_end_date }}<br>Project Start date: {{ tend.t_start_period }} </td>
				<td class="align-middle">Rs.{{ tend.t_price }}</td>
				{% if user.username != '' %}
				<td class="align-middle"><a href="{% url 'bid' tend.id%}" class="btn btn-primary ml-2">BID
				{% endif %}
				</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% endblock %}